#!/usr/bin/env bash
# commit_gradle_wrapper.sh
# Run this ONCE locally to generate gradle-wrapper.jar and commit it.
# After this, the CI "Ensure Gradle wrapper jar" step becomes a <1s no-op.
# See TD-CI-001.
#
# Usage: bash scripts/commit_gradle_wrapper.sh
#
# Prerequisites (any one of):
#   macOS:   brew install gradle          (installs system gradle)
#   Linux:   sdk install gradle 8.3      (via SDKMAN — preferred: exact version)
#   Windows: scoop install gradle  OR  choco install gradle

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ANDROID_DIR="$REPO_ROOT/android"

GRADLE_TARGET_VERSION="8.3"

echo "=== TD-CI-001: Commit Gradle Wrapper ==="
echo "Repo:    $REPO_ROOT"
echo "Android: $ANDROID_DIR"
echo ""

# ── Find a usable gradle ────────────────────────────────────────────────────

GRADLE_BIN=""

# 1. Check SDKMAN candidate for exact 8.3
if [ -d "$HOME/.sdkman/candidates/gradle/$GRADLE_TARGET_VERSION/bin" ]; then
    GRADLE_BIN="$HOME/.sdkman/candidates/gradle/$GRADLE_TARGET_VERSION/bin/gradle"
    echo "Using SDKMAN gradle $GRADLE_TARGET_VERSION"

# 2. Check system gradle
elif command -v gradle &>/dev/null; then
    GRADLE_BIN="$(command -v gradle)"
    GRADLE_VER="$(gradle --version 2>/dev/null | grep 'Gradle ' | awk '{print $2}')"
    echo "Using system gradle: $GRADLE_VER"
    echo "⚠️  Note: wrapper jar will match system version, not $GRADLE_TARGET_VERSION."
    echo "   Prefer: sdk install gradle $GRADLE_TARGET_VERSION && sdk use gradle $GRADLE_TARGET_VERSION"
    echo ""
    read -r -p "Continue with system gradle $GRADLE_VER? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }

else
    echo "ERROR: gradle not found."
    echo ""
    echo "Install options:"
    echo "  SDKMAN (recommended):  sdk install gradle $GRADLE_TARGET_VERSION"
    echo "  macOS:                 brew install gradle"
    echo "  Windows:               scoop install gradle"
    exit 1
fi

echo ""

# ── Generate wrapper ────────────────────────────────────────────────────────

echo "Generating Gradle $GRADLE_TARGET_VERSION wrapper..."
cd "$ANDROID_DIR"
"$GRADLE_BIN" wrapper \
    --gradle-version "$GRADLE_TARGET_VERSION" \
    --distribution-type all

chmod +x gradlew

echo ""
echo "Generated files:"
ls -lh gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar

# Sanity-check the properties file still points to 8.3
DIST_URL=$(grep distributionUrl gradle/wrapper/gradle-wrapper.properties | grep -o "gradle-[0-9.]*" | head -1)
echo ""
echo "Wrapper target: $DIST_URL"
if [[ "$DIST_URL" != "gradle-$GRADLE_TARGET_VERSION" ]]; then
    echo "WARNING: distributionUrl may not match $GRADLE_TARGET_VERSION — check gradle-wrapper.properties"
fi

# ── Commit ──────────────────────────────────────────────────────────────────

echo ""
echo "=== Staging ==="
cd "$REPO_ROOT"
git add android/gradlew android/gradlew.bat android/gradle/wrapper/gradle-wrapper.jar
git status --short android/gradlew android/gradlew.bat android/gradle/wrapper/gradle-wrapper.jar

echo ""
echo "=== Committing ==="
git commit -m "chore: commit gradle wrapper jar (resolves TD-CI-001)

Committed gradle-wrapper.jar generated by Gradle $GRADLE_TARGET_VERSION.
The CI 'Ensure Gradle wrapper jar' step is now a <1s no-op.

Distribution: gradle-$GRADLE_TARGET_VERSION-all
Wrapper: gradle/wrapper/gradle-wrapper.jar"

echo ""
echo "✅ Done. TD-CI-001 resolved."
echo "The CI bootstrap step now runs in <1s (jar present → skip)."
echo ""
echo "Optional next step: remove the bootstrap 'if' block from build.yml"
echo "and simplify to just:  chmod +x android/gradlew"
